function nodeShebang() {
  return '#!/usr/bin/env node';
}

function scriptHeader({ name }) {
  return `${nodeShebang()}
/**
 * Generated by jwebgen.
 * Cross-platform entrypoint for ${name}.
 *
 * Note: during migration, this script may delegate to the legacy bash script on Unix platforms.
 */
`;
}

/** Embedded in generated .mjs files — no npm dependencies besides Node. */
function embeddedSpawnRun() {
  return `
import { spawn } from 'node:child_process';

function run(command, args = [], options = {}) {
  const { cwd, env = process.env } = options;
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, {
      stdio: 'inherit',
      shell: false,
      cwd,
      env
    });
    child.on('error', reject);
    child.on('exit', (code, signal) => {
      if (code === 0) resolve();
      else {
        const hint = signal ? \`signal \${signal}\` : \`code \${code}\`;
        reject(new Error(\`Command failed (\${hint}): \${command} \${args.join(' ')}\`.trim()));
      }
    });
  });
}
`;
}

function delegateToBash({ bashName }) {
  return `${embeddedSpawnRun()}
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

if (process.platform === 'win32') {
  console.error('This action is not available on Windows yet (bash script fallback is unavailable).');
  process.exit(1);
}

const bashPath = path.join(__dirname, ${JSON.stringify(bashName)});
await run('bash', [bashPath, ...process.argv.slice(2)]);
`;
}

export function makeNodeBuildScript() {
  return `${scriptHeader({ name: 'build' })}${embeddedSpawnRun()}
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '../..');

const verbose = String(process.env.JWEBGEN_VERBOSE || '') === '1';
const mvnArgs = ['-DskipTests'];
if (!verbose) mvnArgs.unshift('-B', '-ntp');

const isDev = String(process.env.JWEBGEN_DEV || '') === '1';
const args = isDev ? [...mvnArgs, 'package'] : ['clean', ...mvnArgs, 'package'];
const mavenExecutable = process.platform === 'win32' ? 'mvn.cmd' : 'mvn';

await run(mavenExecutable, args, { cwd: rootDir });
`;
}

export function makeNodeDeployScript() {
  return `${scriptHeader({ name: 'deploy' })}
import path from 'node:path';
import { existsSync } from 'node:fs';
import { cp, mkdir, rm, writeFile, readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '../..');

function parseExports(text) {
  const env = {};
  for (const rawLine of String(text || '').split(/\\r?\\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const m = line.match(/^export\\s+([A-Z0-9_]+)=(.*)$/);
    if (!m) continue;
    const key = m[1];
    let value = m[2].trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith('\\'') && value.endsWith('\\''))) {
      value = value.slice(1, -1);
    }
    env[key] = value;
  }
  return env;
}

async function loadProjectConfig() {
  const cfgPath = path.join(rootDir, '.jwebgen', '.jwebgenrc');
  if (!existsSync(cfgPath)) return {};
  try {
    const raw = await readFile(cfgPath, 'utf8');
    return parseExports(raw);
  } catch {
    return {};
  }
}

async function readMavenAppName() {
  const pomPath = path.join(rootDir, 'pom.xml');
  if (!existsSync(pomPath)) return path.basename(rootDir);
  try {
    const xml = await readFile(pomPath, 'utf8');
    const fm = xml.match(/<finalName>\\s*([^<]+?)\\s*<\\/finalName>/);
    if (fm?.[1]) return fm[1].trim();
    const noParent = xml.replace(/<parent>[\\s\\S]*?<\\/parent>/gi, '');
    const am = noParent.match(/<artifactId>\\s*([^<]+?)\\s*<\\/artifactId>/);
    if (am?.[1]) return am[1].trim();
  } catch {
    /* ignore */
  }
  return path.basename(rootDir);
}

function resolveServerTarget({ cfg }) {
  const v = String(process.env.JWEBGEN_SERVER_TARGET || cfg.JWEBGEN_SERVER_TARGET || '').trim();
  if (v === 'tomcat' || v === 'wildfly') return v;
  return 'tomcat';
}

function isDevMode() {
  return String(process.env.JWEBGEN_DEV || '') === '1';
}

async function ensureDir(p) {
  await mkdir(p, { recursive: true });
}

async function deployTomcat({ cfg, cleanupOnly, appName }) {
  const tomcatHome = String(process.env.TOMCAT_HOME || process.env.TOMCAT10 || cfg.TOMCAT_HOME || cfg.TOMCAT10 || '').trim();
  const defaultHome = process.platform === 'win32' ? '' : '/var/lib/tomcat10';
  const home = tomcatHome || defaultHome;
  if (!home) {
    console.error('Tomcat home is not configured. Set TOMCAT_HOME (or TOMCAT10) in your environment or .jwebgen/.jwebgenrc.');
    process.exit(1);
  }
  const webapps = path.join(home, 'webapps');
  const destExploded = path.join(webapps, appName);
  const destWar = path.join(webapps, appName + '.war');

  await ensureDir(webapps);

  if (cleanupOnly) {
    await rm(destExploded, { recursive: true, force: true });
    await rm(destWar, { force: true });
    console.log('Tomcat cleanup complete: ' + appName);
    return;
  }

  if (isDevMode()) {
    const explodedSrc = path.join(rootDir, 'target', appName);
    if (!existsSync(explodedSrc)) {
      console.error('Build required: missing ' + explodedSrc);
      process.exit(1);
    }
    await rm(destWar, { force: true });
    await rm(destExploded, { recursive: true, force: true });
    await cp(explodedSrc, destExploded, { recursive: true, force: true });
    const ctx = path.join(destExploded, 'META-INF', 'context.xml');
    if (existsSync(ctx)) await writeFile(ctx, await readFile(ctx));
    console.log('Deployed to Tomcat (exploded): ' + destExploded);
    return;
  }

  const targetDir = path.join(rootDir, 'target');
  if (!existsSync(targetDir)) {
    console.error('Build required: target/ directory is missing.');
    process.exit(1);
  }
  const fsPromises = await import('node:fs/promises');
  const entries = await fsPromises.readdir(targetDir);
  const wars = entries.filter((e) => e.endsWith('.war')).sort();
  const warFile = wars[wars.length - 1] ? path.join(targetDir, wars[wars.length - 1]) : '';
  if (!warFile || !existsSync(warFile)) {
    console.error('WAR file not found in target/. Run build first.');
    process.exit(1);
  }
  await rm(destExploded, { recursive: true, force: true });
  await rm(destWar, { force: true });
  await cp(warFile, destWar, { force: true });
  console.log('Deployed to Tomcat: ' + destWar);
}

async function deployWildfly({ cfg, cleanupOnly, appName }) {
  const wildflyHome = String(process.env.WILDFLY_HOME || cfg.WILDFLY_HOME || '/opt/wildfly').trim();
  const deployments = String(process.env.WILDFLY_DEPLOYMENTS || cfg.WILDFLY_DEPLOYMENTS || path.join(wildflyHome, 'standalone', 'deployments')).trim();
  const destWar = path.join(deployments, appName + '.war');

  await ensureDir(deployments);

  const markers = [
    destWar,
    destWar + '.deployed',
    destWar + '.undeployed',
    destWar + '.failed',
    destWar + '.skipdeploy',
    destWar + '.pending',
    destWar + '.isdeploying',
    destWar + '.isundeploying',
    destWar + '.status',
    destWar + '.dodeploy'
  ];

  if (cleanupOnly) {
    await Promise.all(markers.map((p) => rm(p, { force: true })));
    console.log('WildFly cleanup complete: ' + appName);
    return;
  }

  const targetDir = path.join(rootDir, 'target');
  if (!existsSync(targetDir)) {
    console.error('Build required: target/ directory is missing.');
    process.exit(1);
  }
  const fsPromises = await import('node:fs/promises');
  const entries = await fsPromises.readdir(targetDir);
  const wars = entries.filter((e) => e.endsWith('.war')).sort();
  const warFile = wars[wars.length - 1] ? path.join(targetDir, wars[wars.length - 1]) : '';
  if (!warFile || !existsSync(warFile)) {
    console.error('WAR file not found in target/. Run build first.');
    process.exit(1);
  }
  await cp(warFile, destWar, { force: true });
  await writeFile(destWar + '.dodeploy', '');
  console.log('Deployed to WildFly: ' + destWar);
}

const cfg = await loadProjectConfig();
const appName = await readMavenAppName();
const target = resolveServerTarget({ cfg });
const cleanupOnly = process.argv.includes('--cleanup-dev');

if (target === 'tomcat') {
  await deployTomcat({ cfg, cleanupOnly, appName });
} else {
  await deployWildfly({ cfg, cleanupOnly, appName });
}
`;
}

export function makeNodeDevScript() {
  return `${scriptHeader({ name: 'dev' })}${delegateToBash({ bashName: 'dev.sh' })}`;
}

export function makeNodeWatchScript() {
  return `${scriptHeader({ name: 'watch' })}${delegateToBash({ bashName: 'watch.sh' })}`;
}
