import { DEV_DASHBOARD_SCRIPT_TEMPLATE, DEV_WORKER_SCRIPT_TEMPLATE } from './watchEmbeddedTemplates.js';
import { LINUX_DEFAULT_TOMCAT_HOME, LINUX_DEFAULT_WILDFLY_HOME } from '../project/serverPaths.js';

function nodeShebang() {
  return '#!/usr/bin/env node';
}

function scriptHeader({ name }) {
  return `${nodeShebang()}
/**
 * Generated by jwebgen.
 * Node-first cross-platform entrypoint for ${name}.
 * Optional .sh scripts may still exist as Unix convenience wrappers.
 */
`;
}

/** Embedded in generated .mjs files — no npm dependencies besides Node. */
function embeddedSpawnRun() {
  return `
import { spawn, spawnSync } from 'node:child_process';

function run(command, args = [], options = {}) {
  const { cwd, env = process.env } = options;
  const isWindows = process.platform === 'win32';
  const executable = isWindows ? 'cmd.exe' : command;
  const commandArgs = isWindows ? ['/c', command, ...args] : args;
  return new Promise((resolve, reject) => {
    let stderrCaptured = '';
    const child = spawn(executable, commandArgs, {
      stdio: ['ignore', 'inherit', 'pipe'],
      shell: false,
      cwd,
      env
    });
    child.stderr?.on('data', (chunk) => {
      stderrCaptured += String(chunk);
    });
    child.on('error', (err) => {
      err.stderr = stderrCaptured;
      reject(err);
    });
    child.on('exit', (code, signal) => {
      if (code === 0) resolve();
      else {
        const hint = signal ? \`signal \${signal}\` : \`code \${code}\`;
        const err = new Error(\`Command failed (\${hint}): \${command} \${args.join(' ')}\`.trim());
        err.exitCode = code ?? undefined;
        err.stderr = stderrCaptured;
        reject(err);
      }
    });
  });
}
`;
}

export function makeNodeBuildScript() {
  return `${scriptHeader({ name: 'build' })}${embeddedSpawnRun()}
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '../..');

const verbose = String(process.env.JWEBGEN_VERBOSE || '') === '1';
const mvnArgs = ['-DskipTests'];
if (!verbose) mvnArgs.unshift('-B', '-ntp');

const isDev = String(process.env.JWEBGEN_DEV || '') === '1';
const args = isDev ? [...mvnArgs, 'package'] : ['clean', ...mvnArgs, 'package'];
const mavenExecutable = process.platform === 'win32' ? 'mvn.cmd' : 'mvn';

try {
  await run(mavenExecutable, args, { cwd: rootDir });
} catch (err) {
  const stderr = String(err && err.stderr !== undefined ? err.stderr : '');
  const msg = String(err && err.message !== undefined ? err.message : err);
  const combined = msg + '\\n' + stderr;
  const spawnCode = err && err.code;
  const looksLikeMissingMaven =
    spawnCode === 'ENOENT' ||
    (/not recognized as an internal or external command/i.test(combined) && /\\bmvn(\\.cmd)?\\b/i.test(combined));
  if (looksLikeMissingMaven) {
    console.error(
      process.platform === 'win32'
        ? 'Maven not found (expected mvn.cmd on PATH). Install Apache Maven from https://maven.apache.org/ and reopen the terminal.'
        : 'Maven not found (expected mvn on PATH). Install Apache Maven and ensure it is executable.'
    );
  }
  throw err;
}
`;
}

export function makeNodeDeployScript() {
  return `${scriptHeader({ name: 'deploy' })}
import path from 'node:path';
import { existsSync } from 'node:fs';
import { cp, mkdir, rm, writeFile, readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { createInterface } from 'node:readline/promises';
import { spawn, spawnSync } from 'node:child_process';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '../..');

function parseExports(text) {
  const env = {};
  for (const rawLine of String(text || '').split(/\\r?\\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const m = line.match(/^export\\s+([A-Z0-9_]+)=(.*)$/);
    if (!m) continue;
    const key = m[1];
    let value = m[2].trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    env[key] = value;
  }
  return env;
}

async function loadProjectConfig() {
  const cfgPath = path.join(rootDir, '.jwebgen', '.jwebgenrc');
  if (!existsSync(cfgPath)) return {};
  try {
    const raw = await readFile(cfgPath, 'utf8');
    return parseExports(raw);
  } catch {
    return {};
  }
}

async function persistServerTarget(target) {
  const cfgDir = path.join(rootDir, '.jwebgen');
  const cfgPath = path.join(cfgDir, '.jwebgenrc');
  await mkdir(cfgDir, { recursive: true });
  let raw = '';
  if (existsSync(cfgPath)) {
    try {
      raw = await readFile(cfgPath, 'utf8');
    } catch {
      raw = '';
    }
  }
  const line = 'export JWEBGEN_SERVER_TARGET="' + target + '"';
  const hasServerLine = /^\\s*export\\s+JWEBGEN_SERVER_TARGET=.*$/m.test(raw);
  let nextRaw = '';
  if (hasServerLine) {
    nextRaw = raw.replace(/^\\s*export\\s+JWEBGEN_SERVER_TARGET=.*$/m, line);
  } else if (raw.trim().length === 0) {
    nextRaw = line + '\\n';
  } else {
    nextRaw = raw.endsWith('\\n') ? raw + line + '\\n' : raw + '\\n' + line + '\\n';
  }
  await writeFile(cfgPath, nextRaw, 'utf8');
}

async function chooseServerTargetInteractively() {
  if (!process.stdin.isTTY || !process.stdout.isTTY) {
    console.error('Server target is not configured. Run in an interactive terminal to choose tomcat/wildfly,');
    console.error('or set JWEBGEN_SERVER_TARGET (or .jwebgen/.jwebgenrc) before deploying.');
    process.exit(1);
  }
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  try {
    console.log('Select server target for deployment:');
    console.log('  1) tomcat');
    console.log('  2) wildfly');
    while (true) {
      const answer = String(await rl.question('Choose target [1/2, t/w]: ')).trim().toLowerCase();
      if (answer === '1' || answer === 't' || answer === 'tomcat') return 'tomcat';
      if (answer === '2' || answer === 'w' || answer === 'wildfly') return 'wildfly';
      console.log('Invalid choice. Enter 1 (tomcat) or 2 (wildfly).');
    }
  } finally {
    rl.close();
  }
}

async function readMavenAppName() {
  const pomPath = path.join(rootDir, 'pom.xml');
  if (!existsSync(pomPath)) return path.basename(rootDir);
  try {
    const xml = await readFile(pomPath, 'utf8');
    const noParent = xml.replace(/<parent>[\\s\\S]*?<\\/parent>/gi, '');
    const noProfiles = noParent.replace(/<profiles>[\\s\\S]*?<\\/profiles>/gi, '');
    const buildBlock = noProfiles.match(/<build>\\s*([\\s\\S]*?)<\\/build>/i);
    if (buildBlock?.[1]) {
      const fm = buildBlock[1].match(/<finalName>\\s*([^<]+?)\\s*<\\/finalName>/i);
      if (fm?.[1]) return fm[1].trim();
    }
    const am = noProfiles.match(/<artifactId>\\s*([^<]+?)\\s*<\\/artifactId>/);
    if (am?.[1]) return am[1].trim();
  } catch {
    /* ignore */
  }
  return path.basename(rootDir);
}

function resolveServerTarget({ cfg }) {
  const v = String(process.env.JWEBGEN_SERVER_TARGET || cfg.JWEBGEN_SERVER_TARGET || '').trim();
  if (v === 'tomcat' || v === 'wildfly') return v;
  return '';
}

function detectPackageManagers() {
  const has = (bin) => {
    const p = spawnSync(process.platform === 'win32' ? 'where' : 'which', [bin], { stdio: 'ignore' });
    return p.status === 0;
  };
  if (process.platform === 'win32') return { winget: has('winget') };
  if (process.platform === 'darwin') return { brew: has('brew') };
  return { apt: has('apt-get') || has('apt'), dnf: has('dnf'), pacman: has('pacman') };
}

function serverInstallCommands(target) {
  const pm = detectPackageManagers();
  if (target === 'tomcat') {
    if (process.platform === 'win32') return pm.winget ? ['winget install Apache.Tomcat'] : [];
    if (process.platform === 'darwin') return pm.brew ? ['brew install tomcat'] : [];
    const commands = [];
    if (pm.apt) commands.push('sudo apt install -y tomcat10');
    if (pm.dnf) commands.push('sudo dnf install -y tomcat');
    if (pm.pacman) commands.push('sudo pacman -S --noconfirm tomcat10');
    return commands;
  }
  if (process.platform === 'win32') return pm.winget ? ['winget install WildFly.WildFly'] : [];
  if (process.platform === 'darwin') return pm.brew ? ['brew install wildfly-as'] : [];
  const commands = [];
  if (pm.apt) commands.push('sudo apt install -y wildfly');
  if (pm.dnf) commands.push('sudo dnf install -y wildfly');
  if (pm.pacman) commands.push('sudo pacman -S --noconfirm wildfly');
  return commands;
}

function resolveTomcatHome(cfg) {
  const tomcatHome = String(
    process.env.TOMCAT_HOME ||
      process.env.TOMCAT10 ||
      process.env.CATALINA_HOME ||
      cfg.TOMCAT_HOME ||
      cfg.TOMCAT10 ||
      cfg.CATALINA_HOME ||
      ''
  ).trim();
  const defaultHome = process.platform === 'linux' ? '${LINUX_DEFAULT_TOMCAT_HOME}' : '';
  return tomcatHome || defaultHome;
}

function resolveWildflyPaths(cfg) {
  const defaultWildflyHome = process.platform === 'linux' ? '${LINUX_DEFAULT_WILDFLY_HOME}' : '';
  const wildflyHome = String(process.env.WILDFLY_HOME || cfg.WILDFLY_HOME || defaultWildflyHome).trim();
  const deployments = String(
    process.env.WILDFLY_DEPLOYMENTS || cfg.WILDFLY_DEPLOYMENTS || (wildflyHome ? path.join(wildflyHome, 'standalone', 'deployments') : '')
  ).trim();
  return { wildflyHome, deployments };
}

function validateTomcatHome(home) {
  const resolved = home ? path.resolve(home) : '';
  const rootPath = resolved ? path.parse(resolved).root : '';
  if (!resolved || resolved === rootPath) return { ok: false, reason: 'Tomcat home is not configured.' };
  return { ok: true, resolved };
}

function validateWildflyDeployments(deployments) {
  const resolved = deployments ? path.resolve(deployments) : '';
  const rootPath = resolved ? path.parse(resolved).root : '';
  if (!resolved || resolved === rootPath) {
    return { ok: false, reason: 'WildFly deployments path is not configured.' };
  }
  return { ok: true, resolved };
}

function detectServerInstalled(target, cfg) {
  if (target === 'tomcat') {
    const home = resolveTomcatHome(cfg);
    const validated = validateTomcatHome(home);
    if (!validated.ok) return { ok: false, reason: validated.reason };
    if (!existsSync(home)) return { ok: false, reason: 'Tomcat home path was not found: ' + home };
    if (!existsSync(path.join(home, 'webapps'))) return { ok: false, reason: 'Tomcat webapps directory was not found under: ' + home };
    return { ok: true };
  }
  const { wildflyHome, deployments } = resolveWildflyPaths(cfg);
  const validatedDeployments = validateWildflyDeployments(deployments);
  if (!validatedDeployments.ok) return { ok: false, reason: validatedDeployments.reason };
  if (!wildflyHome && !deployments) return { ok: false, reason: 'WildFly path is not configured.' };
  if ((wildflyHome && !existsSync(wildflyHome)) || (deployments && !existsSync(deployments))) {
    return { ok: false, reason: 'WildFly paths were not found.' };
  }
  return { ok: true };
}

async function maybeRunServerInstallAssistant(target, cfg) {
  const status = detectServerInstalled(target, cfg);
  if (status.ok) return true;
  console.error('Selected server (' + target + ') is not installed or not usable.');
  if (status.reason) console.error(status.reason);
  const commands = serverInstallCommands(target);
  if (commands.length === 0) {
    console.error('No guided install method is available for this OS/tooling. Install manually and re-run.');
    return false;
  }
  console.error('Guided install commands for ' + target + ':');
  for (const c of commands) console.error('  ' + c);
  if (!process.stdin.isTTY || !process.stdout.isTTY) return false;
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  try {
    const runNow = String(await rl.question('Run first command now? [y/N]: ')).trim().toLowerCase();
    if (runNow !== 'y' && runNow !== 'yes') return false;
  } finally {
    rl.close();
  }
  const first = commands[0];
  const shell = process.platform === 'win32' ? 'cmd.exe' : 'sh';
  const shellArgs = process.platform === 'win32' ? ['/c', first] : ['-lc', first];
  const r = spawnSync(shell, shellArgs, { stdio: 'inherit' });
  if (r.status !== 0) return false;
  return detectServerInstalled(target, cfg).ok;
}

function isServerRunningQuick(target) {
  if (process.platform === 'win32') {
    const pattern =
      target === 'tomcat'
        ? /tomcat|catalina\\.startup|bootstrap\\.jar/i
        : /wildfly|jboss\\.modules|standalone|jboss\\.home/i;
    const probe = spawnSync(
      'powershell.exe',
      [
        '-NoProfile',
        '-NoLogo',
        '-NonInteractive',
        '-ExecutionPolicy',
        'Bypass',
        '-Command',
        'Get-CimInstance Win32_Process | Where-Object { $_.Name -eq "java.exe" } | ForEach-Object { $_.CommandLine }'
      ],
      { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }
    );
    const text = String(probe.stdout || '');
    if (text.trim()) return pattern.test(text);
  }
  if (process.platform !== 'win32') {
    const pgPattern = target === 'tomcat' ? 'tomcat|catalina' : 'standalone.sh|org.jboss.as.standalone|wildfly';
    const pgrep = spawnSync('pgrep', ['-f', pgPattern], { stdio: 'ignore' });
    if (pgrep.status === 0) return true;
  }
  if (target === 'wildfly') {
    const probe = spawnSync('curl', ['-fsS', '--max-time', '2', 'http://127.0.0.1:9990/'], { stdio: 'ignore' });
    if (probe.status === 0) return true;
  } else {
    const probe = spawnSync('curl', ['-fsS', '--max-time', '2', 'http://127.0.0.1:8080/'], { stdio: 'ignore' });
    if (probe.status === 0) return true;
  }
  if (process.platform === 'linux') {
    const unit = target === 'wildfly' ? 'wildfly' : 'tomcat10';
    const svc = spawnSync('systemctl', ['is-active', '--quiet', unit], { stdio: 'ignore' });
    if (svc.status === 0) return true;
  }
  return false;
}

function isDevMode() {
  return String(process.env.JWEBGEN_DEV || '') === '1';
}

function canAutoSudo() {
  if (process.platform !== 'linux') return false;
  const probe = spawnSync('sudo', ['-n', 'true'], { stdio: 'ignore' });
  // Accept both "already allowed passwordless" and "sudo exists but needs prompt".
  return probe.status === 0 || probe.status === 1;
}

function shellQuote(value) {
  return "'" + String(value).replace(/'/g, "'\\\\''") + "'";
}

function runSudo(args = []) {
  return new Promise((resolve, reject) => {
    const child = spawn('sudo', args, { stdio: 'inherit', shell: false });
    child.on('error', reject);
    child.on('exit', (code, signal) => {
      if (code === 0) resolve();
      else reject(new Error('sudo failed (' + (signal ? 'signal ' + signal : 'code ' + code) + '): ' + args.join(' ')));
    });
  });
}

async function ensureDir(p) {
  await mkdir(p, { recursive: true });
}

async function ensureTomcatDevReloadableContext({ destExploded }) {
  const metaInfDir = path.join(destExploded, 'META-INF');
  const ctx = path.join(metaInfDir, 'context.xml');
  await guardedAcl('deploy (ensure exploded META-INF directory)', async () => {
    await ensureDir(metaInfDir);
  }, async () => runSudo(['mkdir', '-p', metaInfDir]));
  if (!existsSync(ctx)) {
    const defaultContext = '<?xml version="1.0" encoding="UTF-8"?>\\n<Context reloadable="true" />\\n';
    await guardedAcl('deploy (create exploded META-INF/context.xml)', async () => {
      await writeFile(ctx, defaultContext, 'utf8');
    }, async () => runSudo(['sh', '-c', ': > ' + shellQuote(ctx) + ' && chmod 664 ' + shellQuote(ctx)]));
    return;
  }
  let xml = '';
  try {
    xml = await readFile(ctx, 'utf8');
  } catch {
    xml = '';
  }
  if (/reloadable\\s*=\\s*["']true["']/i.test(xml)) return;
  const contextOpenTag = xml.match(/<Context\\b[^>]*>/i);
  if (!contextOpenTag) {
    const merged = (xml.trim().length ? xml.trim() + '\\n' : '') + '<Context reloadable="true" />\\n';
    await guardedAcl('deploy (append reloadable Context metadata)', async () => {
      await writeFile(ctx, merged, 'utf8');
    }, async () => runSudo(['sh', '-c', 'printf %s ' + shellQuote(merged) + ' > ' + shellQuote(ctx)]));
    return;
  }
  const updatedTag = /reloadable\\s*=\\s*["'][^"']*["']/i.test(contextOpenTag[0])
    ? contextOpenTag[0].replace(/reloadable\\s*=\\s*["'][^"']*["']/i, 'reloadable="true"')
    : contextOpenTag[0].replace('<Context', '<Context reloadable="true"');
  const nextXml = xml.replace(contextOpenTag[0], updatedTag);
  if (nextXml === xml) return;
  await guardedAcl('deploy (set Tomcat reloadable=true)', async () => {
    await writeFile(ctx, nextXml, 'utf8');
  }, async () => runSudo(['sh', '-c', 'printf %s ' + shellQuote(nextXml) + ' > ' + shellQuote(ctx)]));
}

function selectWarFile({ targetDir, appName, wars }) {
  const preferred = path.join(targetDir, appName + '.war');
  if (existsSync(preferred)) return preferred;
  if (wars.length === 1) return path.join(targetDir, wars[0]);
  if (wars.length > 1) {
    const candidates = wars.join(', ');
    throw new Error(
      'Multiple WAR files found in target/ without exact match for appName "' + appName + '": ' + candidates
    );
  }
  return '';
}

async function guardedAcl(opLabel, fn, sudoFn) {
  try {
    await fn();
  } catch (err) {
    if (err && (err.code === 'EACCES' || err.code === 'EPERM')) {
      if (typeof sudoFn === 'function' && canAutoSudo()) {
        try {
          await sudoFn();
          return;
        } catch (sudoErr) {
          console.error('Permission denied (' + opLabel + '). Automatic sudo retry failed.');
          console.error(String(sudoErr.message || sudoErr));
          process.exit(1);
        }
      }
      const isWildflyOp = /wildfly/i.test(String(opLabel || ''));
      console.error('Permission denied (' + opLabel + '). The deployment destination must be writable by your user.');
      if (isWildflyOp) {
        console.error(
          'Typical fixes: align WILDFLY_DEPLOYMENTS (or WILDFLY_HOME) with a writable instance for dev,' +
            ' adjust deployments ownership/chmod,' +
            ' or use a group ACL (often needed for Linux packaging under /opt/wildfly/standalone/deployments).'
        );
      } else {
        console.error(
          'Typical fixes: align TOMCAT_HOME/TOMCAT10/CATALINA_HOME with a writable instance for dev,' +
            ' adjust webapps ownership/chmod,' +
            ' or use a group ACL (often needed for Linux packaging under /var/lib/tomcat10).'
        );
      }
      console.error('On Linux, jwebgen auto-retries with sudo when available; otherwise use writable server paths.');
      console.error(String(err.message || err));
      process.exit(1);
    }
    throw err;
  }
}

async function deployTomcat({ cfg, cleanupOnly, appName }) {
  const tomcatHome = String(
    process.env.TOMCAT_HOME ||
      process.env.TOMCAT10 ||
      process.env.CATALINA_HOME ||
      cfg.TOMCAT_HOME ||
      cfg.TOMCAT10 ||
      cfg.CATALINA_HOME ||
      ''
  ).trim();
  const defaultHome = process.platform === 'linux' ? '${LINUX_DEFAULT_TOMCAT_HOME}' : '';
  const home = tomcatHome || defaultHome;
  const validatedHome = validateTomcatHome(home);
  if (!validatedHome.ok) {
    console.error('Tomcat home is not configured. Set TOMCAT_HOME, TOMCAT10, or CATALINA_HOME in your environment or .jwebgen/.jwebgenrc.');
    process.exit(1);
  }
  if (!existsSync(path.join(home, 'webapps'))) {
    console.error('Tomcat webapps directory was not found under: ' + home);
    process.exit(1);
  }
  const webapps = path.join(home, 'webapps');
  const destExploded = path.join(webapps, appName);
  const destWar = path.join(webapps, appName + '.war');

  await guardedAcl('creating Tomcat webapps directory', async () => {
    await ensureDir(webapps);
  }, async () => runSudo(['mkdir', '-p', webapps]));

  if (cleanupOnly) {
    await guardedAcl('cleanup Tomcat exploded app', async () => {
      await rm(destExploded, { recursive: true, force: true });
    }, async () => runSudo(['rm', '-rf', destExploded]));
    await guardedAcl('cleanup Tomcat WAR', async () => {
      await rm(destWar, { force: true });
    }, async () => runSudo(['rm', '-f', destWar]));
    console.log('Tomcat cleanup complete: ' + appName);
    return;
  }

  if (isDevMode()) {
    const explodedSrc = path.join(rootDir, 'target', appName);
    if (!existsSync(explodedSrc)) {
      console.error('Build required: missing ' + explodedSrc);
      process.exit(1);
    }
    await guardedAcl('deploy (remove old Tomcat WAR)', async () => {
      await rm(destWar, { force: true });
    }, async () => runSudo(['rm', '-f', destWar]));
    await guardedAcl('deploy (remove old exploded tree)', async () => {
      await rm(destExploded, { recursive: true, force: true });
    }, async () => runSudo(['rm', '-rf', destExploded]));
    await guardedAcl('deploy exploded copy into Tomcat webapps', async () => {
      await cp(explodedSrc, destExploded, { recursive: true, force: true });
    }, async () => runSudo(['cp', '-a', explodedSrc, destExploded]));
    await ensureTomcatDevReloadableContext({ destExploded });
    await guardedAcl('deploy (touch exploded META-INF/context.xml)', async () => {
      const ctx = path.join(destExploded, 'META-INF', 'context.xml');
      if (existsSync(ctx)) await writeFile(ctx, await readFile(ctx));
    }, async () => {
      const ctx = path.join(destExploded, 'META-INF', 'context.xml');
      await runSudo(['sh', '-c', 'if [ -f ' + shellQuote(ctx) + ' ]; then touch ' + shellQuote(ctx) + '; fi']);
    });
    console.log('Deployed to Tomcat (exploded): ' + destExploded);
    return;
  }

  const targetDir = path.join(rootDir, 'target');
  if (!existsSync(targetDir)) {
    console.error('Build required: target/ directory is missing.');
    process.exit(1);
  }
  const fsPromises = await import('node:fs/promises');
  const entries = await fsPromises.readdir(targetDir);
  const wars = entries.filter((e) => e.endsWith('.war')).sort();
  const warFile = selectWarFile({ targetDir, appName, wars });
  if (!warFile || !existsSync(warFile)) {
    console.error('WAR file not found in target/. Run build first.');
    process.exit(1);
  }
  await guardedAcl('deploy (refresh exploded dir)', async () => {
    await rm(destExploded, { recursive: true, force: true });
  }, async () => runSudo(['rm', '-rf', destExploded]));
  await guardedAcl('deploy (remove old Tomcat WAR)', async () => {
    await rm(destWar, { force: true });
  }, async () => runSudo(['rm', '-f', destWar]));
  await guardedAcl('copy WAR into Tomcat webapps', async () => {
    await cp(warFile, destWar, { force: true });
  }, async () => runSudo(['cp', '-f', warFile, destWar]));
  console.log('Deployed to Tomcat: ' + destWar);
}

async function deployWildfly({ cfg, cleanupOnly, appName }) {
  const defaultWildflyHome = process.platform === 'linux' ? '${LINUX_DEFAULT_WILDFLY_HOME}' : '';
  const wildflyHome = String(process.env.WILDFLY_HOME || cfg.WILDFLY_HOME || defaultWildflyHome).trim();
  const deployments = String(
    process.env.WILDFLY_DEPLOYMENTS || cfg.WILDFLY_DEPLOYMENTS || (wildflyHome ? path.join(wildflyHome, 'standalone', 'deployments') : '')
  ).trim();
  const resolvedDeployments = deployments ? path.resolve(deployments) : '';
  const validatedDeployments = validateWildflyDeployments(resolvedDeployments);
  if (!validatedDeployments.ok) {
    console.error('WildFly deployments path is not configured. Set WILDFLY_DEPLOYMENTS (or WILDFLY_HOME) in env/.jwebgenrc.');
    process.exit(1);
  }
  const destWar = path.join(resolvedDeployments, appName + '.war');

  await guardedAcl('ensure WildFly deployments directory', async () => {
    await ensureDir(resolvedDeployments);
  }, async () => runSudo(['mkdir', '-p', resolvedDeployments]));

  const markers = [
    destWar,
    destWar + '.deployed',
    destWar + '.undeployed',
    destWar + '.failed',
    destWar + '.skipdeploy',
    destWar + '.pending',
    destWar + '.isdeploying',
    destWar + '.isundeploying',
    destWar + '.status',
    destWar + '.dodeploy'
  ];

  if (cleanupOnly) {
    await guardedAcl('WildFly cleanup markers', async () => {
      await Promise.all(markers.map((p) => rm(p, { force: true })));
    }, async () => runSudo(['rm', '-f', ...markers]));
    console.log('WildFly cleanup complete: ' + appName);
    return;
  }

  const targetDir = path.join(rootDir, 'target');
  if (!existsSync(targetDir)) {
    console.error('Build required: target/ directory is missing.');
    process.exit(1);
  }
  const fsPromises = await import('node:fs/promises');
  const entries = await fsPromises.readdir(targetDir);
  const wars = entries.filter((e) => e.endsWith('.war')).sort();
  const warFile = selectWarFile({ targetDir, appName, wars });
  if (!warFile || !existsSync(warFile)) {
    console.error('WAR file not found in target/. Run build first.');
    process.exit(1);
  }
  await guardedAcl('copy WAR to WildFly deployments', async () => {
    await cp(warFile, destWar, { force: true });
  }, async () => runSudo(['cp', '-f', warFile, destWar]));
  await guardedAcl('WildFly deploy marker (.dodeploy)', async () => {
    await writeFile(destWar + '.dodeploy', '');
  }, async () => runSudo(['sh', '-c', ': > ' + shellQuote(destWar + '.dodeploy')]));
  console.log('Deployed to WildFly: ' + destWar);
}

const cfg = await loadProjectConfig();
const appName = await readMavenAppName();
let target = resolveServerTarget({ cfg });
if (!target) {
  target = await chooseServerTargetInteractively();
  await persistServerTarget(target);
}
const cleanupOnly = process.argv.includes('--cleanup-dev');
if (!cleanupOnly) {
  const installed = await maybeRunServerInstallAssistant(target, cfg);
  if (!installed) process.exit(1);
  if (!isServerRunningQuick(target)) {
    console.error('Selected server is installed but currently down.');
    console.error('__JWEBGEN_EVENT__ server_down');
    process.exit(1);
  }
}

if (target === 'tomcat') {
  await deployTomcat({ cfg, cleanupOnly, appName });
} else {
  await deployWildfly({ cfg, cleanupOnly, appName });
}
`;
}

export function makeNodeDevScript() {
  // Node-first dev entrypoint. Equivalent to running watch.sh with JWEBGEN_DEV=1.
  // Embed worker/dashboard code so generated projects remain standalone.
  return `${scriptHeader({ name: 'dev' })}
import path from 'node:path';
import { existsSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { spawn, spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { createInterface } from 'node:readline/promises';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '../..');

function parseExports(text) {
  const env = {};
  for (const rawLine of String(text || '').split(/\\r?\\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const m = line.match(/^export\\s+([A-Z0-9_]+)=(.*)$/);
    if (!m) continue;
    const key = m[1];
    let value = m[2].trim();
    if ((value.startsWith('\"') && value.endsWith('\"')) || (value.startsWith(\"'\") && value.endsWith(\"'\"))) {
      value = value.slice(1, -1);
    }
    env[key] = value;
  }
  return env;
}

async function loadProjectConfig() {
  const cfgPath = path.join(rootDir, '.jwebgen', '.jwebgenrc');
  if (!existsSync(cfgPath)) return {};
  try {
    const raw = await (await import('node:fs/promises')).readFile(cfgPath, 'utf8');
    return parseExports(raw);
  } catch {
    return {};
  }
}

async function persistServerTarget(target) {
  const cfgDir = path.join(rootDir, '.jwebgen');
  const cfgPath = path.join(cfgDir, '.jwebgenrc');
  await mkdir(cfgDir, { recursive: true });
  let raw = '';
  if (existsSync(cfgPath)) {
    try { raw = await (await import('node:fs/promises')).readFile(cfgPath, 'utf8'); } catch { raw = ''; }
  }
  const line = 'export JWEBGEN_SERVER_TARGET=\"' + target + '\"';
  const has = /^\\s*export\\s+JWEBGEN_SERVER_TARGET=.*$/m.test(raw);
  let next = '';
  if (has) next = raw.replace(/^\\s*export\\s+JWEBGEN_SERVER_TARGET=.*$/m, line);
  else if (raw.trim().length === 0) next = line + '\\n';
  else next = raw.endsWith('\\n') ? raw + line + '\\n' : raw + '\\n' + line + '\\n';
  await writeFile(cfgPath, next, 'utf8');
}

async function chooseServerTargetInteractively() {
  if (!process.stdin.isTTY || !process.stdout.isTTY) {
    console.error('Server target is not configured. Run in an interactive terminal to choose tomcat/wildfly,');
    console.error('or set JWEBGEN_SERVER_TARGET (or .jwebgen/.jwebgenrc) before running dev.');
    process.exit(1);
  }
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  try {
    console.log('Select server target for dev:');
    console.log('  1) tomcat');
    console.log('  2) wildfly');
    while (true) {
      const a = String(await rl.question('Choose target [1/2, t/w]: ')).trim().toLowerCase();
      if (a === '1' || a === 't' || a === 'tomcat') return 'tomcat';
      if (a === '2' || a === 'w' || a === 'wildfly') return 'wildfly';
      console.log('Invalid choice. Enter 1 (tomcat) or 2 (wildfly).');
    }
  } finally { rl.close(); }
}

function resolveServerTarget({ cfg }) {
  const v = String(process.env.JWEBGEN_SERVER_TARGET || cfg.JWEBGEN_SERVER_TARGET || '').trim();
  if (v === 'tomcat' || v === 'wildfly') return v;
  return '';
}

function detectPackageManagers() {
  const has = (bin) => {
    const p = spawnSync(process.platform === 'win32' ? 'where' : 'which', [bin], { stdio: 'ignore' });
    return p.status === 0;
  };
  if (process.platform === 'win32') return { winget: has('winget') };
  if (process.platform === 'darwin') return { brew: has('brew') };
  return { apt: has('apt-get') || has('apt'), dnf: has('dnf'), pacman: has('pacman') };
}

function serverInstallCommands(target) {
  const pm = detectPackageManagers();
  if (target === 'tomcat') {
    if (process.platform === 'win32') return pm.winget ? ['winget install Apache.Tomcat'] : [];
    if (process.platform === 'darwin') return pm.brew ? ['brew install tomcat'] : [];
    const commands = [];
    if (pm.apt) commands.push('sudo apt install -y tomcat10');
    if (pm.dnf) commands.push('sudo dnf install -y tomcat');
    if (pm.pacman) commands.push('sudo pacman -S --noconfirm tomcat10');
    return commands;
  }
  if (process.platform === 'win32') return pm.winget ? ['winget install WildFly.WildFly'] : [];
  if (process.platform === 'darwin') return pm.brew ? ['brew install wildfly-as'] : [];
  const commands = [];
  if (pm.apt) commands.push('sudo apt install -y wildfly');
  if (pm.dnf) commands.push('sudo dnf install -y wildfly');
  if (pm.pacman) commands.push('sudo pacman -S --noconfirm wildfly');
  return commands;
}

function resolveTomcatHome(cfg) {
  const tomcatHome = String(
    process.env.TOMCAT_HOME ||
      process.env.TOMCAT10 ||
      process.env.CATALINA_HOME ||
      cfg.TOMCAT_HOME ||
      cfg.TOMCAT10 ||
      cfg.CATALINA_HOME ||
      ''
  ).trim();
  const defaultHome = process.platform === 'linux' ? '${LINUX_DEFAULT_TOMCAT_HOME}' : '';
  return tomcatHome || defaultHome;
}

function resolveWildflyPaths(cfg) {
  const defaultWildflyHome = process.platform === 'linux' ? '${LINUX_DEFAULT_WILDFLY_HOME}' : '';
  const wildflyHome = String(process.env.WILDFLY_HOME || cfg.WILDFLY_HOME || defaultWildflyHome).trim();
  const deployments = String(
    process.env.WILDFLY_DEPLOYMENTS || cfg.WILDFLY_DEPLOYMENTS || (wildflyHome ? path.join(wildflyHome, 'standalone', 'deployments') : '')
  ).trim();
  return { wildflyHome, deployments };
}

function detectServerInstalled(target, cfg) {
  if (target === 'tomcat') {
    const home = resolveTomcatHome(cfg);
    if (!home) return { ok: false, reason: 'Tomcat home is not configured.' };
    if (!existsSync(home)) return { ok: false, reason: 'Tomcat home path was not found: ' + home };
    if (!existsSync(path.join(home, 'webapps'))) return { ok: false, reason: 'Tomcat webapps directory was not found under: ' + home };
    return { ok: true };
  }
  const { wildflyHome, deployments } = resolveWildflyPaths(cfg);
  if (!wildflyHome && !deployments) return { ok: false, reason: 'WildFly path is not configured.' };
  if ((wildflyHome && !existsSync(wildflyHome)) || (deployments && !existsSync(deployments))) {
    return { ok: false, reason: 'WildFly paths were not found.' };
  }
  return { ok: true };
}

async function maybeRunServerInstallAssistant(target, cfg) {
  const status = detectServerInstalled(target, cfg);
  if (status.ok) return true;
  console.error('Selected server (' + target + ') is not installed or not usable.');
  if (status.reason) console.error(status.reason);
  const commands = serverInstallCommands(target);
  if (commands.length === 0) {
    console.error('No guided install method is available for this OS/tooling. Install manually and re-run.');
    return false;
  }
  console.error('Guided install commands for ' + target + ':');
  for (const c of commands) console.error('  ' + c);
  if (!process.stdin.isTTY || !process.stdout.isTTY) return false;
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  try {
    const runNow = String(await rl.question('Run first command now? [y/N]: ')).trim().toLowerCase();
    if (runNow !== 'y' && runNow !== 'yes') return false;
  } finally {
    rl.close();
  }
  const first = commands[0];
  const shell = process.platform === 'win32' ? 'cmd.exe' : 'sh';
  const shellArgs = process.platform === 'win32' ? ['/c', first] : ['-lc', first];
  const r = spawnSync(shell, shellArgs, { stdio: 'inherit' });
  if (r.status !== 0) return false;
  return detectServerInstalled(target, cfg).ok;
}

async function readMavenAppName() {
  const pomPath = path.join(rootDir, 'pom.xml');
  if (!existsSync(pomPath)) return path.basename(rootDir);
  try {
    const { readFile } = await import('node:fs/promises');
    const xml = await readFile(pomPath, 'utf8');
    const noParent = xml.replace(/<parent>[\\s\\S]*?<\\/parent>/gi, '');
    const noProfiles = noParent.replace(/<profiles>[\\s\\S]*?<\\/profiles>/gi, '');
    const buildBlock = noProfiles.match(/<build>\\s*([\\s\\S]*?)<\\/build>/i);
    if (buildBlock?.[1]) {
      const fm = buildBlock[1].match(/<finalName>\\s*([^<]+?)\\s*<\\/finalName>/i);
      if (fm?.[1]) return fm[1].trim();
    }
    const am = noProfiles.match(/<artifactId>\\s*([^<]+?)\\s*<\\/artifactId>/);
    if (am?.[1]) return am[1].trim();
  } catch {
    /* ignore */
  }
  return path.basename(rootDir);
}

const cfg = await loadProjectConfig();
let target = resolveServerTarget({ cfg });
if (!target) { target = await chooseServerTargetInteractively(); await persistServerTarget(target); }
const installed = await maybeRunServerInstallAssistant(target, cfg);
if (!installed) process.exit(1);
const appName = await readMavenAppName();

const workDir = rootDir;
const stateFile = path.join(workDir, '.jwebgen', '.jwebgen-dev-state.json');
const eventsFile = path.join(workDir, '.jwebgen', '.jwebgen-dev-events.jsonl');
const pauseFile = path.join(workDir, '.jwebgen', '.jwebgen-ui-pause');
const commandFile = path.join(workDir, '.jwebgen', '.jwebgen-dev-command.json');
const workerScript = path.join(workDir, '.jwebgen', '.jwebgen-worker.mjs');
const dashboardScript = path.join(workDir, '.jwebgen', '.jwebgen-dashboard.mjs');

await mkdir(path.join(workDir, '.jwebgen'), { recursive: true });
const DEV_WORKER_SCRIPT_TEMPLATE = ${JSON.stringify(DEV_WORKER_SCRIPT_TEMPLATE)};
const DEV_DASHBOARD_SCRIPT_TEMPLATE = ${JSON.stringify(DEV_DASHBOARD_SCRIPT_TEMPLATE)};
await writeFile(workerScript, DEV_WORKER_SCRIPT_TEMPLATE, 'utf8');
await writeFile(dashboardScript, DEV_DASHBOARD_SCRIPT_TEMPLATE, 'utf8');

const env = { ...process.env, JWEBGEN_DEV: '1', JWEBGEN_SERVER_TARGET: target, JWEBGEN_APP_NAME: appName };
const worker = spawn(process.execPath, [workerScript, stateFile, eventsFile, pauseFile, String(process.pid), commandFile], { cwd: workDir, env, stdio: 'inherit' });
const dash = spawn(process.execPath, [dashboardScript, stateFile, pauseFile, commandFile, String(process.pid)], { cwd: workDir, env, stdio: ['ignore', 'inherit', 'inherit'] });

const shutdown = () => {
  try { worker.kill('SIGTERM'); } catch {}
  try { dash.kill('SIGTERM'); } catch {}
};
process.on('SIGINT', () => { shutdown(); process.exit(130); });
process.on('SIGTERM', () => { shutdown(); process.exit(143); });
worker.on('exit', (code) => { shutdown(); process.exit(code == null ? 1 : code); });
`;
}

export function makeNodeWatchScript() {
  // Node-first watch entrypoint (same runtime as dev, without forcing JWEBGEN_DEV=1).
  return `${scriptHeader({ name: 'watch' })}\n// This script intentionally reuses dev.mjs implementation.\nimport { fileURLToPath } from 'node:url';\nimport path from 'node:path';\nimport { spawn } from 'node:child_process';\nconst __filename = fileURLToPath(import.meta.url);\nconst __dirname = path.dirname(__filename);\nconst dev = path.join(__dirname, 'dev.mjs');\nconst child = spawn(process.execPath, [dev, ...process.argv.slice(2)], { stdio: 'inherit' });\nchild.on('exit', (code) => process.exit(code == null ? 1 : code));\n`;
}
